services:
  - type: pserv
    name: render-subnet-router
    env: docker
    envVars:
      - key: TAILSCALE_AUTHKEY
        sync: false
      - key: TAILSCALE_VERSION
        value: 1.14.3
      - key: ADVERTISE_ROUTES
        value: 10.0.0.0/8
    disk:
      name: tailscale-state
      mountPath: /var/lib/tailscale
      sizeGB: 1

